export interface Student {
    ID?                    : number,
    lastname?              : string,
    firstname?             : string,
    middlename?            : string,
    fullname?              : string,
    gender?                : string,
    bday?                  : Date,
    home_address?          : string,
    lrn?                   : string,
    religion_id?           : number,
    graduated?             : number,
    nationality_id?        : number,
    school_id?             : number,
    student_cat_id?        : string,
    Guardian?              : string,
    remarks?               : string,
    nationality?           : string,
    is_enrollment?         : number,
    father?                : {
                                lastname?      : string,
                                firstname?     : string,
                                middlename?    : string,
                                pname?         : string,
                                email?         : string,
                                home_address?  : string,
                                mobile?        : string
                              },
    mother?                : {
                                lastname?      : string,
                                firstname?     : string,
                                middlename?    : string,
                                pname?         : string,
                                email?         : string,
                                home_address?  : string,
                                mobile?        : string
                              },
    guardian?              : {
                                lastname?      : string,
                                firstname?     : string,
                                middlename?    : string,
                                pname?         : string,
                                email?         : string,
                                home_address?  : string,
                                mobile?        : string
                              },
  }
